version: '3.7'

services:
  nginx:
    dockerfile: 
      - ./nginx/Dockerfile
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"

  web:
    build: 
      - ./web
    image: 
      - coinpurse:latest
    container_name: coinpurse
    expose:
      - 5000
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    env_file: 
      - ./.env.prod
    command:
      gunicorn --bind 0.0.0.0:5000 wsgi:app



    

