version: '3.7'

services:
  coinpurse:
    build: .
    image: coinpurse:latest
    
    ports:
      - "5000:5000"

    volumes:
      # - .:/code
      - data:/data 

volumes:
  data:
    
    # env_file: 
    # - ./.env.dev
    # environment:
    #     - FLASK_APP=wsgi.py
    #     - FLASK_ENV=development