version: '3.7'

services:
  coinpurse:
    build: .
    image: coinpurse:latest
    
    # command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    # dockerfile: ./Dockerfile 
    ports:
      - 5000:5000
    env_file: 
      # - ./.env.dev
      - FLASK_APP=web/wsgi.py
      - FLASK_ENV=development