version: '3.7'

services:
  web:
    build: .
    image: coinpurse:latest
    
    ports:
      - "5000:5000"

    volumes:      
      - .:/data 
    
    env_file: 
      - ./.env.dev

    command:
      flask run -h 0.0.0.0

volumes:
  data:
    driver: local
