"""AddUserToSettings

Revision ID: 6e215d9d729f
Revises: 69f6d627d519
Create Date: 2021-08-28 08:59:12.309788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e215d9d729f'
down_revision = '69f6d627d519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Settings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Settings', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Settings', type_='foreignkey')
    op.drop_column('Settings', 'user_id')
    # ### end Alembic commands ###
