"""AddCharacterRef

Revision ID: 8ec91050a664
Revises: 1dd00dcf2bd7
Create Date: 2020-11-23 16:02:48.602540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec91050a664'
down_revision = '1dd00dcf2bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Entries', sa.Column('character_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Entries', 'Characters', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Entries', type_='foreignkey')
    op.drop_column('Entries', 'character_id')
    # ### end Alembic commands ###
